Repository MemeInvestor/memeinvestor_bot, pull requests merged in 2018-05, with the labels that each got.

#34 changed formula
  src/main.py
Labels: Addition

#39 Rewrote it :)
  .gitignore
  Dockerfile
  docker-compose.yml
  docker/config.py
  docker/entrypoint.sh
  requirements.txt
  src/api.py
  src/calculator.py
  src/database.py
  src/example.config.py
  src/main.py
  src/models/__init__.py
  src/models/base.py
  src/models/comments.py
  src/models/investments.py
  src/models/investors.py
  src/models/submissions.py
  src/submitter.py
Labels: enhancement

#41 Bug killing & API improvement
  src/api.py
  src/calculator.py
  src/main.py
  src/models/base.py
  src/models/investments.py
  src/models/investors.py
Labels: bug, enhancement

#44 Added some anti-spam message
  src/message.py
Labels: enhancement

#42 Modified win/lose behaviour
  README.md
  data/investment_return_multiplier_thresholding.png
  src/calculator.py
Labels: enhancement

#40 Add !top command to show leaderboard
  README.md
  src/main.py
  src/message.py
Labels: enhancement
