Repository MemeInvestor/memeinvestor_bot, pull requests merged in 2018-11, with the labels that each got.

#261 Number literals/suffixes
  src/main.py
Labels: enhancement

#268 Updated the bash script so it can be launched from anywhere on the ma…
  backup.sh
Labels: enhancement

#270 Added a maintenance part to the readme and added goaccess caddy confi…
  .goaccess.caddy.conf
  README.md
Labels: enhancement, in progress

#276 Added snow effect javascript to our website.
  docs/index.html
  docs/js/libs/snowstorm-min.js
  docs/js/libs/snowstorm.js
  docs/leaderboards.html
  docs/resources/christmas/logo240_christmas.png
  docs/user.html
Labels: enhancement, in progress

#278 Fixed the crazy speeds
  docs/js/libs/snowstorm-min.js
Labels: in progress
