Repository MemeInvestor/memeinvestor_bot, pull requests merged in 2018-06, with the labels that each got.

#51 Added js & other styling to the page
  docs/css/style.css
  docs/index.html
  docs/js/libs/countup.min.js
  docs/js/main.js
  docs/resources/logo-600.png
  docs/resources/logo1.png
  docs/resources/logo240.png
  docs/resources/logo400.png
  docs/testApiData.json
Labels: enhancement

#47 Fixed comments in calculate and added break-even behaviour
  src/calculator.py
  src/message.py
Labels: enhancement

#68 Change date format to YYYY-MM-DD
  docs/index.html
Labels: Addition

#66 SQL investment success update now based on change.
  src/calculator.py
Labels: Addition

#70 Added investment calculator
  docs/css/style.css
  docs/index.html
  docs/js/main.js
Labels: enhancement

#72 Consolidated config to a single location for easier setup
  .env.example
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  docker/config.py
  docker/entrypoint.sh
  src/config.py
  src/example.config.py
Labels: enhancement, help wanted

#81 Added more authors and some details.
  README.md
  src/message.py
Labels: enhancement

#88 Ignore stale transaction requests by checking comment age
  src/main.py
Labels: bug, enhancement

#94 Add .vscode to .gitignore
  .gitignore
Labels: Addition

#104 Skip stickied posts. Fixes #90
  src/submitter.py
Labels: bug, enhancement

#102 Added balance to investments messages. Fixes #91
  src/calculator.py
  src/message.py
Labels: enhancement

#85 Automatically set up the database on first run if it's missing. Fixes #73
  README.md
  src/main.py
  src/models.py
  src/models/__init__.py
  src/models/investments.py
  src/models/investors.py
Labels: enhancement

#123 Stream comment replies instead of querying inbox
  src/main.py
Labels: enhancement

#139 Add academic paper describing the formula
  README.md
  data/investment_return_multiplier.png
  data/investment_return_multiplier_thresholding.png
  data/paper.org
  data/paper_figure_1.png
  data/paper_figure_2.png
  data/references.bib
  docs/resources/graph1.jpg
  docs/resources/paper.pdf
Labels: enhancement

#144 Added command line tool to perform test calculations with the formula.
  src/formula-test.py
Labels: enhancement
